# Generated by Django 6.0.4 on 2026-04-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('usdot_number', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('dock_count', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('cdl_number', models.CharField(blank=True, max_length=40)),
                ('truck_number', models.CharField(max_length=30)),
                ('trailer_number', models.CharField(blank=True, max_length=30)),
                ('load_reference', models.CharField(max_length=40, unique=True)),
                ('appointment_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('dock_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('on_dock', 'On Dock'), ('unloading', 'Unloading'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('cargo_description', models.CharField(blank=True, max_length=200)),
                ('temperature_controlled', models.BooleanField(default=False)),
                ('safety_notes', models.TextField(blank=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='checkins.carrier')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='checkins.facility')),
            ],
            options={
                'ordering': ['status', '-arrival_time'],
            },
        ),
    ]
